#:schema node_modules/wrangler/config-schema.json
name = "demg-remix"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-22"

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "pnpm build"

[[workflows]]
name = "demg-test-workflow"
binding = "TEST_WORKFLOW"
class_name = "TestWorkflow"
